-- ============================================================================
-- LedgerFlow V1: initial schema
--
-- Design notes (full rationale in docs/database-design.md):
--  * Money is BIGINT minor units (cents). Floating point is never used.
--  * IDs are UUIDv7 generated by the application (time-ordered => B-tree
--    friendly inserts and clean keyset pagination).
--  * Enumerations are TEXT + CHECK constraints, not Postgres ENUM types:
--    adding a value is a plain metadata change instead of an ALTER TYPE
--    with locking caveats.
--  * transactions and ledger_entries are range-partitioned by month on
--    created_at from day one: both are append-only, unbounded, and almost
--    always queried by time window.
--  * The double-entry invariant (entries of one transaction sum to zero) is
--    enforced IN THE DATABASE via a deferred constraint trigger, attached to
--    every ledger partition by the partition-maintenance function.
--  * ledger_entries and audit_logs are append-only: UPDATE/DELETE are
--    rejected by triggers regardless of application bugs.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Helpers
-- ----------------------------------------------------------------------------

CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE FUNCTION reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% rows are append-only (attempted %)', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'prohibited_sql_statement_attempted';
END;
$$;

-- ----------------------------------------------------------------------------
-- users
-- ----------------------------------------------------------------------------

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    full_name     TEXT        NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'USER'
                  CHECK (role IN ('USER', 'ADMIN')),
    status        TEXT        NOT NULL DEFAULT 'ACTIVE'
                  CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness without the citext extension.
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- accounts + account_balances
--
-- account_balances is a separate 1:1 table on purpose: it is the single row
-- receiving SELECT ... FOR UPDATE + UPDATE on every money movement. Keeping it
-- narrow separates the hot write path from the cold account metadata and keeps
-- HOT updates likely (no index on balance).
--
-- min_balance encodes the floor per account: 0 for user wallets, NULL
-- (unbounded) for system accounts, which legitimately go negative in
-- double-entry terms (they mirror money entering/leaving the platform).
-- ----------------------------------------------------------------------------

CREATE TABLE accounts (
    id         UUID PRIMARY KEY,
    user_id    UUID        REFERENCES users (id),
    type       TEXT        NOT NULL
               CHECK (type IN ('USER_WALLET', 'MERCHANT', 'SYSTEM_CASH', 'SYSTEM_FEES', 'SYSTEM_SUSPENSE')),
    currency   CHAR(3)     NOT NULL,
    status     TEXT        NOT NULL DEFAULT 'ACTIVE'
               CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- System accounts belong to the platform, user-facing accounts to a user.
    CONSTRAINT chk_accounts_ownership
        CHECK ((type LIKE 'SYSTEM\_%') = (user_id IS NULL))
);

CREATE INDEX ix_accounts_user_id ON accounts (user_id) WHERE user_id IS NOT NULL;

CREATE TRIGGER trg_accounts_updated_at
    BEFORE UPDATE ON accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE account_balances (
    account_id  UUID PRIMARY KEY REFERENCES accounts (id),
    balance     BIGINT      NOT NULL DEFAULT 0,
    min_balance BIGINT,               -- NULL => no floor (system accounts)
    version     BIGINT      NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Final backstop against double spending, independent of application code.
    CONSTRAINT chk_balance_floor CHECK (min_balance IS NULL OR balance >= min_balance)
);

CREATE TRIGGER trg_account_balances_updated_at
    BEFORE UPDATE ON account_balances
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- idempotency_keys
--
-- Uniqueness is scoped (user, endpoint, key): two users may coincidentally
-- pick the same key, and one client key must not collide across endpoints.
-- request_hash detects key reuse with a different payload (client bug => 422).
-- ----------------------------------------------------------------------------

CREATE TABLE idempotency_keys (
    id              UUID PRIMARY KEY,
    user_id         UUID        NOT NULL REFERENCES users (id),
    endpoint        TEXT        NOT NULL,
    idem_key        TEXT        NOT NULL,
    request_hash    TEXT        NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'IN_PROGRESS'
                    CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
    response_status INT,
    response_body   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT ux_idempotency UNIQUE (user_id, endpoint, idem_key)
);

CREATE TRIGGER trg_idempotency_keys_updated_at
    BEFORE UPDATE ON idempotency_keys
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- transactions (partitioned by month)
--
-- PK must include the partition key, hence (id, created_at). Uniqueness of id
-- alone is guaranteed by construction (UUIDv7) and enforced per-partition.
-- ----------------------------------------------------------------------------

CREATE TABLE transactions (
    id                     UUID        NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    type                   TEXT        NOT NULL
                           CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'PAYMENT', 'REFUND')),
    status                 TEXT        NOT NULL DEFAULT 'PENDING'
                           CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED')),
    amount                 BIGINT      NOT NULL CHECK (amount > 0),
    currency               CHAR(3)     NOT NULL,
    source_account_id      UUID        REFERENCES accounts (id),
    destination_account_id UUID        REFERENCES accounts (id),
    idempotency_key_id     UUID        REFERENCES idempotency_keys (id),
    correlation_id         UUID,
    description            TEXT,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TRIGGER trg_transactions_updated_at
    BEFORE UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- ledger_entries (partitioned by month)
--
-- Amounts are SIGNED: positive credits the account, negative debits it.
-- direction is a stored generated column purely for readability/analytics.
-- created_at always equals the parent transaction's created_at (enforced by
-- the composite FK), so both tables prune on the same time predicate.
-- ----------------------------------------------------------------------------

CREATE TABLE ledger_entries (
    id             UUID        NOT NULL,
    transaction_id UUID        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    account_id     UUID        NOT NULL REFERENCES accounts (id),
    amount         BIGINT      NOT NULL CHECK (amount <> 0),
    currency       CHAR(3)     NOT NULL,
    direction      TEXT        GENERATED ALWAYS AS (CASE WHEN amount > 0 THEN 'CREDIT' ELSE 'DEBIT' END) STORED,
    PRIMARY KEY (id, created_at),
    FOREIGN KEY (transaction_id, created_at) REFERENCES transactions (id, created_at)
) PARTITION BY RANGE (created_at);

-- Append-only: block UPDATE/DELETE at the database level.
CREATE TRIGGER trg_ledger_entries_append_only
    BEFORE UPDATE OR DELETE ON ledger_entries
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- The double-entry invariant: at COMMIT, each transaction's entries sum to 0.
-- Executed as a DEFERRED constraint trigger so all entries of the transaction
-- are visible when it runs. Attached per-partition by create_month_partitions
-- (constraint triggers cannot be created on partitioned parents).
CREATE FUNCTION assert_transaction_balanced() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    entry_sum BIGINT;
BEGIN
    SELECT COALESCE(SUM(amount), 0) INTO entry_sum
    FROM ledger_entries
    WHERE transaction_id = NEW.transaction_id;

    IF entry_sum <> 0 THEN
        RAISE EXCEPTION 'unbalanced ledger transaction %: entries sum to %', NEW.transaction_id, entry_sum
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

-- ----------------------------------------------------------------------------
-- Partition maintenance
--
-- Creates monthly partitions for transactions and ledger_entries N months
-- ahead, attaching the balance constraint trigger to each new ledger
-- partition. Called by V1 for the current + next 3 months and by the
-- application on a schedule. No DEFAULT partition on purpose: a default
-- silently absorbs mis-ranged rows and blocks clean partition creation;
-- we prefer failing loudly + monitoring partition coverage.
-- ----------------------------------------------------------------------------

CREATE FUNCTION create_month_partitions(months_ahead INT DEFAULT 3) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    month_start DATE;
    month_end   DATE;
    suffix      TEXT;
    m           INT;
BEGIN
    FOR m IN 0..months_ahead LOOP
        month_start := date_trunc('month', now())::date + make_interval(months => m);
        month_end   := month_start + INTERVAL '1 month';
        suffix      := to_char(month_start, 'YYYY_MM');

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS transactions_%s PARTITION OF transactions
             FOR VALUES FROM (%L) TO (%L)',
            suffix, month_start, month_end);

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS ledger_entries_%s PARTITION OF ledger_entries
             FOR VALUES FROM (%L) TO (%L)',
            suffix, month_start, month_end);

        -- Attach the deferred zero-sum constraint trigger (idempotent).
        IF NOT EXISTS (
            SELECT 1 FROM pg_trigger
            WHERE tgname = 'trg_ledger_balanced_' || suffix
        ) THEN
            EXECUTE format(
                'CREATE CONSTRAINT TRIGGER trg_ledger_balanced_%s
                 AFTER INSERT ON ledger_entries_%s
                 DEFERRABLE INITIALLY DEFERRED
                 FOR EACH ROW EXECUTE FUNCTION assert_transaction_balanced()',
                suffix, suffix);
        END IF;
    END LOOP;
END;
$$;

SELECT create_month_partitions(3);

-- ----------------------------------------------------------------------------
-- transaction_events: status-change history for a transaction
-- ----------------------------------------------------------------------------

CREATE TABLE transaction_events (
    id                     UUID PRIMARY KEY,
    transaction_id         UUID        NOT NULL,
    transaction_created_at TIMESTAMPTZ NOT NULL,
    from_status            TEXT,
    to_status              TEXT        NOT NULL,
    reason                 TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (transaction_id, transaction_created_at) REFERENCES transactions (id, created_at)
);

CREATE INDEX ix_transaction_events_txn ON transaction_events (transaction_id);

-- ----------------------------------------------------------------------------
-- payment_methods: tokenized external references only, never raw PANs
-- ----------------------------------------------------------------------------

CREATE TABLE payment_methods (
    id         UUID PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users (id),
    type       TEXT        NOT NULL CHECK (type IN ('CARD', 'BANK_ACCOUNT')),
    token      TEXT        NOT NULL, -- opaque token from an external vault/processor
    last_four  CHAR(4)     NOT NULL,
    status     TEXT        NOT NULL DEFAULT 'ACTIVE'
               CHECK (status IN ('ACTIVE', 'EXPIRED', 'REMOVED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_payment_methods_user ON payment_methods (user_id);

CREATE TRIGGER trg_payment_methods_updated_at
    BEFORE UPDATE ON payment_methods
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- payments / refunds / disputes
-- ----------------------------------------------------------------------------

CREATE TABLE payments (
    id                     UUID PRIMARY KEY,
    payer_user_id          UUID        NOT NULL REFERENCES users (id),
    payment_method_id      UUID        REFERENCES payment_methods (id),
    source_account_id      UUID        REFERENCES accounts (id),
    destination_account_id UUID        NOT NULL REFERENCES accounts (id),
    amount                 BIGINT      NOT NULL CHECK (amount > 0),
    refunded_amount        BIGINT      NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),
    currency               CHAR(3)     NOT NULL,
    status                 TEXT        NOT NULL DEFAULT 'PENDING'
                           CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED',
                                             'PARTIALLY_REFUNDED', 'REFUNDED')),
    transaction_id         UUID,
    transaction_created_at TIMESTAMPTZ,
    failure_reason         TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (transaction_id, transaction_created_at) REFERENCES transactions (id, created_at),
    -- A payment can never be refunded beyond its own amount, no matter what
    -- the application does. Refund flows lock the payment row FOR UPDATE.
    CONSTRAINT chk_refund_within_amount CHECK (refunded_amount <= amount)
);

CREATE INDEX ix_payments_payer ON payments (payer_user_id, created_at DESC);

CREATE TRIGGER trg_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE refunds (
    id                     UUID PRIMARY KEY,
    payment_id             UUID        NOT NULL REFERENCES payments (id),
    amount                 BIGINT      NOT NULL CHECK (amount > 0),
    status                 TEXT        NOT NULL DEFAULT 'PENDING'
                           CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    reason                 TEXT,
    transaction_id         UUID,
    transaction_created_at TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (transaction_id, transaction_created_at) REFERENCES transactions (id, created_at)
);

CREATE INDEX ix_refunds_payment ON refunds (payment_id);

CREATE TRIGGER trg_refunds_updated_at
    BEFORE UPDATE ON refunds
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE disputes (
    id          UUID PRIMARY KEY,
    payment_id  UUID        NOT NULL REFERENCES payments (id),
    opened_by   UUID        NOT NULL REFERENCES users (id),
    status      TEXT        NOT NULL DEFAULT 'OPEN'
                CHECK (status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED_MERCHANT', 'RESOLVED_CUSTOMER')),
    reason      TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ
);

CREATE INDEX ix_disputes_payment ON disputes (payment_id);

CREATE TRIGGER trg_disputes_updated_at
    BEFORE UPDATE ON disputes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- outbox_events + processed_events (transactional outbox, at-least-once)
-- ----------------------------------------------------------------------------

CREATE TABLE outbox_events (
    id              UUID PRIMARY KEY,
    aggregate_type  TEXT        NOT NULL,
    aggregate_id    UUID        NOT NULL,
    event_type      TEXT        NOT NULL,
    topic           TEXT        NOT NULL,
    payload         JSONB       NOT NULL,
    headers         JSONB,
    status          TEXT        NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    attempts        INT         NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ
);

-- The publisher polls only unpublished rows; a partial index keeps that poll
-- O(pending) instead of O(all events ever).
CREATE INDEX ix_outbox_pending
    ON outbox_events (next_attempt_at, created_at)
    WHERE status = 'PENDING';

-- Consumer-side dedup for at-least-once delivery.
CREATE TABLE processed_events (
    consumer_group TEXT        NOT NULL,
    event_id       UUID        NOT NULL,
    processed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (consumer_group, event_id)
);

-- ----------------------------------------------------------------------------
-- audit_logs (append-only)
-- ----------------------------------------------------------------------------

CREATE TABLE audit_logs (
    id             UUID PRIMARY KEY,
    occurred_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_user_id  UUID        REFERENCES users (id),
    actor_type     TEXT        NOT NULL DEFAULT 'USER' CHECK (actor_type IN ('USER', 'SYSTEM')),
    action         TEXT        NOT NULL,
    resource_type  TEXT        NOT NULL,
    resource_id    TEXT        NOT NULL,
    previous_state JSONB,
    new_state      JSONB,
    request_id     TEXT,
    correlation_id UUID,
    service        TEXT        NOT NULL,
    reason         TEXT
);

CREATE INDEX ix_audit_logs_resource ON audit_logs (resource_type, resource_id, occurred_at DESC);
CREATE INDEX ix_audit_logs_occurred ON audit_logs (occurred_at DESC);

CREATE TRIGGER trg_audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- ----------------------------------------------------------------------------
-- fraud_decisions + notifications
-- ----------------------------------------------------------------------------

CREATE TABLE fraud_decisions (
    id                     UUID PRIMARY KEY,
    payment_id             UUID        REFERENCES payments (id),
    transaction_id         UUID,
    transaction_created_at TIMESTAMPTZ,
    verdict                TEXT        NOT NULL CHECK (verdict IN ('APPROVED', 'REVIEW', 'REJECTED')),
    score                  NUMERIC(5, 2),
    rule_hits              JSONB       NOT NULL DEFAULT '[]',
    evaluated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (transaction_id, transaction_created_at) REFERENCES transactions (id, created_at)
);

CREATE INDEX ix_fraud_decisions_payment ON fraud_decisions (payment_id);

CREATE TABLE notifications (
    id         UUID PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users (id),
    type       TEXT        NOT NULL,
    channel    TEXT        NOT NULL CHECK (channel IN ('EMAIL', 'SMS', 'IN_APP')),
    status     TEXT        NOT NULL DEFAULT 'PENDING'
               CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    payload    JSONB       NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at    TIMESTAMPTZ
);

CREATE INDEX ix_notifications_user ON notifications (user_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- Seed: platform system accounts (fixed UUIDs, referenced by configuration).
-- Deposits/withdrawals are proper double-entry against SYSTEM_CASH; fees
-- accrue to SYSTEM_FEES. System balances have no floor (min_balance NULL).
-- ----------------------------------------------------------------------------

INSERT INTO accounts (id, user_id, type, currency, status, name) VALUES
    ('00000000-0000-7000-8000-000000000001', NULL, 'SYSTEM_CASH',     'USD', 'ACTIVE', 'Platform cash (USD)'),
    ('00000000-0000-7000-8000-000000000002', NULL, 'SYSTEM_FEES',     'USD', 'ACTIVE', 'Platform fees (USD)'),
    ('00000000-0000-7000-8000-000000000003', NULL, 'SYSTEM_SUSPENSE', 'USD', 'ACTIVE', 'Platform suspense (USD)');

INSERT INTO account_balances (account_id, balance, min_balance) VALUES
    ('00000000-0000-7000-8000-000000000001', 0, NULL),
    ('00000000-0000-7000-8000-000000000002', 0, NULL),
    ('00000000-0000-7000-8000-000000000003', 0, NULL);
